apiVersion: apps/v1
kind: Deployment
metadata:
  name: kidjig-deploy
  labels:
    app: kidjig-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kidjig-deploy
  template:
    metadata:
      labels:
        app: kidjig-deploy
    spec:
      containers:
      - name: kidjig-project
        image: vihu360/kidjig-project:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: / 
            port: 80
          initialDelaySeconds: 30  
          periodSeconds: 10

